# Generated by Django 5.0.2 on 2024-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cores_bordado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('valor', models.FloatField()),
                ('unidade_de_medida', models.CharField(choices=[('Un', 'Unidade'), ('m', 'Metro'), ('g', 'Grama')], max_length=2)),
                ('classificacao', models.CharField(choices=[('A', 'Aviamentos'), ('T', 'Tecido'), ('P', 'Peças'), ('L', 'Linha')], max_length=1)),
                ('cores', models.ManyToManyField(related_name='+', to='estoque.cor')),
            ],
        ),
    ]
