# Generated by Django 5.0.2 on 2024-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suprimento',
            name='classificacao',
            field=models.CharField(choices=[('P', 'Peças'), ('A', 'Aviamentos'), ('T', 'Tecido'), ('L', 'Linha')], max_length=1),
        ),
        migrations.AlterField(
            model_name='suprimento',
            name='unidade_de_medida',
            field=models.CharField(choices=[('m', 'Metro'), ('g', 'Grama'), ('Un', 'Unidade')], max_length=2),
        ),
    ]
