# Generated by Django 5.0.2 on 2024-02-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_suprimento_classificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='hex',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suprimento',
            name='classificacao',
            field=models.CharField(choices=[('A', 'Aviamentos'), ('T', 'Tecido'), ('L', 'Linha'), ('P', 'Peças')], max_length=1),
        ),
        migrations.AlterField(
            model_name='suprimento',
            name='unidade_de_medida',
            field=models.CharField(choices=[('g', 'Grama'), ('m', 'Metro'), ('Un', 'Unidade')], max_length=2),
        ),
    ]
