# Generated by Django 5.0.2 on 2024-02-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanho',
            name='complexidade',
            field=models.IntegerField(choices=[(2, 'Normal'), (5, 'Muito Difícil'), (4, 'Difícil'), (3, 'Avançado'), (1, 'Facil')]),
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('validacoes', models.CharField(choices=[('R', 'Requerido'), ('A', 'Aviso'), ('O', 'Opicional')], max_length=1)),
                ('primeira_pagina', models.BooleanField()),
                ('complexidade', models.IntegerField(choices=[(2, 'Normal'), (5, 'Muito Difícil'), (4, 'Difícil'), (3, 'Avançado'), (1, 'Facil')])),
                ('esquema_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='venda.esquemaproduto')),
            ],
        ),
        migrations.DeleteModel(
            name='Medidas',
        ),
    ]
