# Generated by Django 5.0.2 on 2024-03-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_alter_tamanho_complexidade_medida_delete_medidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esquemaproduto',
            old_name='suprimento',
            new_name='suprimentos',
        ),
        migrations.AlterField(
            model_name='medida',
            name='complexidade',
            field=models.IntegerField(choices=[(5, 'Muito Difícil'), (3, 'Avançado'), (4, 'Difícil'), (2, 'Normal'), (1, 'Facil')]),
        ),
        migrations.AlterField(
            model_name='medida',
            name='validacoes',
            field=models.CharField(choices=[('A', 'Aviso'), ('O', 'Opicional'), ('R', 'Requerido')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='complexidade',
            field=models.IntegerField(choices=[(5, 'Muito Difícil'), (3, 'Avançado'), (4, 'Difícil'), (2, 'Normal'), (1, 'Facil')]),
        ),
    ]
