# Generated by Django 5.0.2 on 2024-02-27 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0002_alter_suprimento_classificacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('locais_de_bordado_sugeridos', models.CharField(max_length=50)),
                ('valor_base', models.FloatField()),
                ('suprimento', models.ManyToManyField(related_name='+', to='estoque.suprimento')),
            ],
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('validacoes', models.CharField(choices=[('R', 'Requerido'), ('A', 'Aviso'), ('O', 'Opicional')], max_length=1)),
                ('primeira_pagina', models.BooleanField()),
                ('complexidade', models.IntegerField(choices=[(1, 'Facil'), (4, 'Difícil'), (2, 'Normal'), (3, 'Avançado'), (5, 'Muito Difícil')])),
                ('esquema_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='venda.esquemaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Modelagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('requerido', models.BooleanField()),
                ('tipo', models.CharField(choices=[('U', 'Unico'), ('V', 'Varias Escolhas')], max_length=1)),
                ('esquema_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='venda.esquemaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoModelagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('modelagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='venda.modelagem')),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3)),
                ('complexidade', models.IntegerField(choices=[(1, 'Facil'), (4, 'Difícil'), (2, 'Normal'), (3, 'Avançado'), (5, 'Muito Difícil')])),
                ('esquema_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='venda.esquemaproduto')),
            ],
        ),
    ]
